[global]
error_log = /proc/self/fd/2
daemonize = no

[www]
listen = /run/php/php-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

user = www-data
group = www-data

pm = dynamic
pm.max_children = 8
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 500

; Logging
access.log = /proc/self/fd/2
catch_workers_output = yes
decorate_workers_output = no

; Keep env vars for Docker / Compose
clear_env = no
